services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zara_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zara_network

  crawler:
    build:
      context: .
      dockerfile: crawler.Dockerfile
    container_name: crawler
    depends_on:
      - mysql
    networks:
      - zara_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - zara_network

volumes:
  mysql_data:

networks:
  zara_network:
    driver: bridge
